#include <check.h>

Suite* kfs_common_suite(void);
Suite* kfs_rmdir_suite(void);
Suite* kfs_mkdir_suite(void);
Suite* kfs_read_suite(void);
Suite* kfs_access_suite(void);
Suite* kfs_open_suite(void);
Suite* kfs_create_suite(void);
Suite* kfs_write_suite(void);
Suite* kfs_release_suite(void);
Suite* kfs_chmod_suite(void);
Suite* kfs_link_suite(void);
Suite* kfs_unlink_suite(void);
Suite* kfs_rename_suite(void);
Suite* kfs_symlink_suite(void);
Suite* kfs_flush_suite(void);
Suite* kfs_truncate_suite(void);
Suite* kfs_ftruncate_suite(void);
Suite* kfs_readlink_suite(void);
Suite* kfs_fsync_suite(void);
Suite* kfs_opendir_suite(void);